-- ============================================================
-- FASE 0 - Sistema Web de Gestión Taller Mecánico "JUAN" (SGTMJ)
-- Motor: SQL Server 2012+  /  Tipos: VARCHAR, INT, DECIMAL, DATETIME
-- ============================================================

-- 1) CREAR BASE DE DATOS
IF DB_ID('TallerJuanDB') IS NOT NULL
BEGIN
    ALTER DATABASE TallerJuanDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE TallerJuanDB;
END
GO
CREATE DATABASE TallerJuanDB;
GO
USE TallerJuanDB;
GO

-- ============================================================
-- 2) TABLAS MAESTRAS PRINCIPALES (8 entidades del DER)
-- ============================================================

CREATE TABLE CLIENTE (
    CEDULA          VARCHAR(20)   NOT NULL,
    NOMBRE          VARCHAR(100)  NOT NULL,
    TELEFONO        VARCHAR(20)   NULL,
    DIRECCION       VARCHAR(200)  NULL,
    CORREO          VARCHAR(100)  NULL,
    TIPO            VARCHAR(20)   NULL,            -- particular / empresarial
    FECHA_REGISTRO  DATETIME      NOT NULL DEFAULT GETDATE(),
    ESTADO          VARCHAR(10)   NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CEDULA)
);
GO

CREATE TABLE VEHICULO (
    PLACA            VARCHAR(10)  NOT NULL,
    MARCA            VARCHAR(50)  NOT NULL,
    MODELO           VARCHAR(50)  NOT NULL,
    ANIO             INT          NULL,
    COLOR            VARCHAR(30)  NULL,
    NUMERO_CHASIS    VARCHAR(50)  NULL,
    NUMERO_MOTOR     VARCHAR(50)  NULL,
    TIPO_COMBUSTIBLE VARCHAR(20)  NULL,
    KILOMETRAJE      INT          NULL,
    CLIENTE_CEDULA   VARCHAR(20)  NOT NULL,
    ESTADO           VARCHAR(10)  NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT PK_VEHICULO PRIMARY KEY (PLACA),
    CONSTRAINT FK_VEHICULO_CLIENTE FOREIGN KEY (CLIENTE_CEDULA)
        REFERENCES CLIENTE(CEDULA)
);
GO

CREATE TABLE ROL (
    ID_ROL    INT          IDENTITY(1,1) NOT NULL,
    NOMBRE    VARCHAR(50)  NOT NULL,
    ESTADO    VARCHAR(10)  NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL),
    CONSTRAINT UQ_ROL_NOMBRE UNIQUE (NOMBRE)
);
GO

CREATE TABLE EMPLEADO (
    CEDULA        VARCHAR(20)   NOT NULL,
    NOMBRE        VARCHAR(100)  NOT NULL,
    TELEFONO      VARCHAR(20)   NULL,
    DIRECCION     VARCHAR(200)  NULL,
    CARGO         VARCHAR(30)   NOT NULL,
    FECHA_INGRESO DATETIME      NOT NULL DEFAULT GETDATE(),
    SALARIO       DECIMAL(10,2) NULL,
    ESPECIALIDAD  VARCHAR(100)  NULL,
    USUARIO       VARCHAR(50)   NOT NULL,
    CONTRASENA    VARCHAR(255)  NOT NULL,         -- SHA-256 (64 hex chars)
    ID_ROL        INT           NOT NULL,
    ESTADO        VARCHAR(10)   NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (CEDULA),
    CONSTRAINT UQ_EMPLEADO_USUARIO UNIQUE (USUARIO),
    CONSTRAINT FK_EMPLEADO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
);
GO

CREATE TABLE PRODUCTO (
    CODIGO        VARCHAR(20)   NOT NULL,
    NOMBRE        VARCHAR(100)  NOT NULL,
    CATEGORIA     VARCHAR(50)   NULL,
    MARCA         VARCHAR(50)   NULL,
    DESCRIPCION   VARCHAR(500)  NULL,
    STOCK_ACTUAL  INT           NOT NULL DEFAULT 0,
    STOCK_MINIMO  INT           NOT NULL DEFAULT 0,
    PRECIO_COMPRA DECIMAL(10,2) NULL,
    PRECIO_VENTA  DECIMAL(10,2) NOT NULL DEFAULT 0,
    ESTADO        VARCHAR(10)   NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO)
);
GO

CREATE TABLE ORDEN_TRABAJO (
    NUMERO_ORDEN        INT           IDENTITY(1,1) NOT NULL,
    FECHA_INGRESO       DATETIME      NOT NULL DEFAULT GETDATE(),
    KILOMETRAJE_INGRESO INT           NULL,
    MOTIVO_VISITA       VARCHAR(200)  NULL,
    DESCRIPCION_PROBLEMA VARCHAR(500) NULL,
    ESTADO              VARCHAR(30)   NOT NULL DEFAULT 'RECIBIDO',
    FECHA_ENTREGA       DATETIME      NULL,
    VEHICULO_PLACA      VARCHAR(10)   NOT NULL,
    EMPLEADO_CEDULA     VARCHAR(20)   NOT NULL,
    CONSTRAINT PK_ORDEN_TRABAJO PRIMARY KEY (NUMERO_ORDEN),
    CONSTRAINT FK_OT_VEHICULO FOREIGN KEY (VEHICULO_PLACA) REFERENCES VEHICULO(PLACA),
    CONSTRAINT FK_OT_EMPLEADO FOREIGN KEY (EMPLEADO_CEDULA) REFERENCES EMPLEADO(CEDULA)
);
GO

CREATE TABLE DIAGNOSTICO (
    ID_DIAGNOSTICO      INT           IDENTITY(1,1) NOT NULL,
    DESCRIPCION         VARCHAR(1000) NOT NULL,
    TIEMPO_ESTIMADO     DECIMAL(5,2)  NULL,
    COSTO_ESTIMADO      DECIMAL(10,2) NULL,
    FECHA               DATETIME      NOT NULL DEFAULT GETDATE(),
    ORDEN_TRABAJO_NUMERO_ORDEN INT    NOT NULL,
    CONSTRAINT PK_DIAGNOSTICO PRIMARY KEY (ID_DIAGNOSTICO),
    CONSTRAINT FK_DIAG_OT FOREIGN KEY (ORDEN_TRABAJO_NUMERO_ORDEN)
        REFERENCES ORDEN_TRABAJO(NUMERO_ORDEN)
);
GO

CREATE TABLE COTIZACION (
    NUMERO_COTIZACION  INT           IDENTITY(1,1) NOT NULL,
    FECHA_EMISION      DATETIME      NOT NULL DEFAULT GETDATE(),
    VALIDEZ_DIAS       INT           NULL,
    SUBTOTAL_SERVICIOS DECIMAL(10,2) NOT NULL DEFAULT 0,
    SUBTOTAL_REPUESTOS DECIMAL(10,2) NOT NULL DEFAULT 0,
    IMPUESTOS          DECIMAL(10,2) NOT NULL DEFAULT 0,
    TOTAL              DECIMAL(10,2) NOT NULL DEFAULT 0,
    ESTADO             VARCHAR(20)   NOT NULL DEFAULT 'PENDIENTE',
    CLIENTE_CEDULA     VARCHAR(20)   NOT NULL,
    VEHICULO_PLACA     VARCHAR(10)   NOT NULL,
    CONSTRAINT PK_COTIZACION PRIMARY KEY (NUMERO_COTIZACION),
    CONSTRAINT FK_COT_CLIENTE FOREIGN KEY (CLIENTE_CEDULA) REFERENCES CLIENTE(CEDULA),
    CONSTRAINT FK_COT_VEHICULO FOREIGN KEY (VEHICULO_PLACA) REFERENCES VEHICULO(PLACA)
);
GO

CREATE TABLE FACTURA (
    NUMERO_FACTURA  INT           IDENTITY(1,1) NOT NULL,
    FECHA_EMISION   DATETIME      NOT NULL DEFAULT GETDATE(),
    SUBTOTAL        DECIMAL(10,2) NOT NULL DEFAULT 0,
    IVA             DECIMAL(10,2) NOT NULL DEFAULT 0,
    TOTAL           DECIMAL(10,2) NOT NULL DEFAULT 0,
    ESTADO          VARCHAR(20)   NOT NULL DEFAULT 'EMITIDA',
    ORDEN_TRABAJO_NUMERO_ORDEN INT NOT NULL,
    CONSTRAINT PK_FACTURA PRIMARY KEY (NUMERO_FACTURA),
    -- Relación 1:1 con ORDEN_TRABAJO forzada por UNIQUE sobre la FK
    CONSTRAINT UQ_FACTURA_ORDEN UNIQUE (ORDEN_TRABAJO_NUMERO_ORDEN),
    CONSTRAINT FK_FAC_OT FOREIGN KEY (ORDEN_TRABAJO_NUMERO_ORDEN)
        REFERENCES ORDEN_TRABAJO(NUMERO_ORDEN)
);
GO

-- ============================================================
-- 3) TABLAS MAESTRAS / INTERMEDIAS  (resolución de N:M)
-- ============================================================

-- DETALLE_COTIZACION  (COTIZACION <-> PRODUCTO)  N:M
CREATE TABLE DETALLE_COTIZACION (
    COTIZACION_NUMERO_COTIZACION INT          NOT NULL,
    PRODUCTO_CODIGO              VARCHAR(20)   NOT NULL,
    ID_DETALLE_COTIZACION        INT           IDENTITY(1,1) NOT NULL,
    DESCRIPCION                  VARCHAR(200)  NULL,
    TIPO                         VARCHAR(20)   NULL,   -- SERVICIO / REPUESTO
    CANTIDAD                     INT           NOT NULL DEFAULT 1,
    PRECIO_UNITARIO              DECIMAL(10,2) NOT NULL DEFAULT 0,
    SUBTOTAL                     DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT PK_DETALLE_COTIZACION PRIMARY KEY (COTIZACION_NUMERO_COTIZACION, PRODUCTO_CODIGO),
    CONSTRAINT FK_DETCOT_COTIZACION FOREIGN KEY (COTIZACION_NUMERO_COTIZACION)
        REFERENCES COTIZACION(NUMERO_COTIZACION),
    CONSTRAINT FK_DETCOT_PRODUCTO FOREIGN KEY (PRODUCTO_CODIGO)
        REFERENCES PRODUCTO(CODIGO)
);
GO

-- DETALLE_FACTURA  (FACTURA <-> PRODUCTO)  N:M
CREATE TABLE DETALLE_FACTURA (
    FACTURA_NUMERO_FACTURA INT          NOT NULL,
    PRODUCTO_CODIGO        VARCHAR(20)   NOT NULL,
    ID_DETALLE             INT           IDENTITY(1,1) NOT NULL,
    DESCRIPCION            VARCHAR(200)  NULL,
    TIPO                   VARCHAR(20)   NULL,   -- SERVICIO / REPUESTO
    CANTIDAD               INT           NOT NULL DEFAULT 1,
    PRECIO_UNITARIO        DECIMAL(10,2) NOT NULL DEFAULT 0,
    SUBTOTAL               DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (FACTURA_NUMERO_FACTURA, PRODUCTO_CODIGO),
    CONSTRAINT FK_DETFAC_FACTURA FOREIGN KEY (FACTURA_NUMERO_FACTURA)
        REFERENCES FACTURA(NUMERO_FACTURA),
    CONSTRAINT FK_DETFAC_PRODUCTO FOREIGN KEY (PRODUCTO_CODIGO)
        REFERENCES PRODUCTO(CODIGO)
);
GO

-- MOVIMIENTO_INVENTARIO  (PRODUCTO <-> ORDEN_TRABAJO)  N:M
CREATE TABLE MOVIMIENTO_INVENTARIO (
    PRODUCTO_CODIGO            VARCHAR(20)  NOT NULL,
    ORDEN_TRABAJO_NUMERO_ORDEN INT         NOT NULL,
    ID_MOVIMIENTO             INT          IDENTITY(1,1) NOT NULL,
    TIPO                      VARCHAR(20)  NOT NULL,   -- INGRESO / SALIDA
    FECHA                     DATETIME     NOT NULL DEFAULT GETDATE(),
    MOTIVO                    VARCHAR(200) NULL,
    CANTIDAD                  INT          NOT NULL,
    CONSTRAINT PK_MOV_INVENTARIO PRIMARY KEY (PRODUCTO_CODIGO, ORDEN_TRABAJO_NUMERO_ORDEN, ID_MOVIMIENTO),
    CONSTRAINT FK_MOV_PRODUCTO FOREIGN KEY (PRODUCTO_CODIGO)
        REFERENCES PRODUCTO(CODIGO),
    CONSTRAINT FK_MOV_OT FOREIGN KEY (ORDEN_TRABAJO_NUMERO_ORDEN)
        REFERENCES ORDEN_TRABAJO(NUMERO_ORDEN)
);
GO

-- ============================================================
-- 4) TABLAS DE SEGURIDAD (permisos y roles)
-- ============================================================

CREATE TABLE PERMISO (
    ID_PERMISO  INT          IDENTITY(1,1) NOT NULL,
    CLAVE       VARCHAR(50)  NOT NULL,   -- ej: CLIENTES_VER, FACTURA_ANULAR
    DESCRIPCION VARCHAR(150) NOT NULL,
    MODULO      VARCHAR(50)  NOT NULL,
    CONSTRAINT PK_PERMISO PRIMARY KEY (ID_PERMISO),
    CONSTRAINT UQ_PERMISO_CLAVE UNIQUE (CLAVE)
);
GO

-- ROL <-> PERMISO   N:M  (el admin asigna/quita permisos a cada rol)
CREATE TABLE ROL_PERMISO (
    ID_ROL     INT NOT NULL,
    ID_PERMISO INT NOT NULL,
    CONSTRAINT PK_ROL_PERMISO PRIMARY KEY (ID_ROL, ID_PERMISO),
    CONSTRAINT FK_RP_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    CONSTRAINT FK_RP_PERMISO FOREIGN KEY (ID_PERMISO) REFERENCES PERMISO(ID_PERMISO)
);
GO

-- ============================================================
-- 5) BITÁCORA DE AUDITORÍA (RNF19)
-- ============================================================
CREATE TABLE AUDITORIA (
    ID_AUDITORIA INT          IDENTITY(1,1) NOT NULL,
    FECHA        DATETIME     NOT NULL DEFAULT GETDATE(),
    USUARIO      VARCHAR(50)  NOT NULL,
    MODULO       VARCHAR(50)  NOT NULL,
    OPERACION    VARCHAR(200) NOT NULL,
    CONSTRAINT PK_AUDITORIA PRIMARY KEY (ID_AUDITORIA)
);
GO

-- ============================================================
-- 6) DATOS INICIALES: ROLES, PERMISOS, USUARIO ADMIN "juan"
-- ============================================================

INSERT INTO ROL (NOMBRE) VALUES ('Administrador'), ('Recepcionista'), ('Mecanico'), ('Encargado de Inventario');
GO

INSERT INTO PERMISO (CLAVE, DESCRIPCION, MODULO) VALUES
('CLIENTES_VER',       'Consultar clientes',           'Clientes'),
('CLIENTES_EDITAR',    'Registrar/editar clientes',    'Clientes'),
('CLIENTES_ELIMINAR',  'Eliminar clientes',            'Clientes'),
('VEHICULOS_VER',      'Consultar vehiculos',          'Vehiculos'),
('VEHICULOS_EDITAR',   'Registrar/editar vehiculos',   'Vehiculos'),
('VEHICULOS_ELIMINAR', 'Eliminar vehiculos',           'Vehiculos'),
('ORDENES_VER',        'Consultar ordenes de trabajo', 'Ordenes'),
('ORDENES_EDITAR',     'Crear/actualizar ordenes',     'Ordenes'),
('ORDENES_CERRAR',     'Cerrar ordenes de trabajo',    'Ordenes'),
('DIAGNOSTICO_EDITAR', 'Registrar diagnostico',        'Ordenes'),
('INVENTARIO_VER',     'Consultar stock',              'Inventario'),
('INVENTARIO_EDITAR',  'Registrar productos/movimientos','Inventario'),
('EMPLEADOS_VER',      'Consultar empleados',          'Empleados'),
('EMPLEADOS_EDITAR',   'Registrar/editar empleados',   'Empleados'),
('EMPLEADOS_ELIMINAR', 'Eliminar empleados',           'Empleados'),
('ROLES_GESTIONAR',    'Asignar roles y permisos',     'Seguridad'),
('COTIZACIONES_VER',   'Consultar cotizaciones',       'Cotizaciones'),
('COTIZACIONES_EDITAR','Generar/aprobar cotizaciones', 'Cotizaciones'),
('FACTURAS_VER',       'Consultar facturas',           'Facturacion'),
('FACTURAS_EMITIR',    'Emitir facturas',              'Facturacion'),
('FACTURAS_ANULAR',    'Anular facturas',              'Facturacion'),
('REPORTES_VER',       'Consultar reportes',           'Reportes'),
('TARIFAS_EDITAR',     'Modificar tarifas',            'Configuracion');
GO

-- El Administrador (ID_ROL = 1) recibe TODOS los permisos
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT 1, ID_PERMISO FROM PERMISO;
GO

-- Usuario administrador "juan" / contraseña "juan" (SHA-256, hex mayúsculas)
INSERT INTO EMPLEADO (CEDULA, NOMBRE, CARGO, USUARIO, CONTRASENA, ID_ROL, ESTADO)
VALUES (
    '00000000',
    'Juan Administrador',
    'Administrador',
    'juan',
    UPPER(CONVERT(VARCHAR(64), HASHBYTES('SHA2_256', CONVERT(VARBINARY(MAX), 'juan')), 2)),
    1,
    'ACTIVO'
);
GO

-- ============================================================
-- 7) PROCEDIMIENTOS ALMACENADOS
-- ============================================================

-- ---- LOGIN ----
CREATE PROCEDURE sp_Login
    @Usuario    VARCHAR(50),
    @HashClave  VARCHAR(64)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT E.CEDULA, E.NOMBRE, E.USUARIO, E.CARGO, E.ID_ROL, R.NOMBRE AS ROL_NOMBRE
    FROM EMPLEADO E
    INNER JOIN ROL R ON E.ID_ROL = R.ID_ROL
    WHERE E.USUARIO = @Usuario
      AND E.CONTRASENA = @HashClave
      AND E.ESTADO = 'ACTIVO';
END
GO

-- ---- PERMISOS POR ROL ----
CREATE PROCEDURE sp_PermisosPorRol
    @IdRol INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT P.ID_PERMISO, P.CLAVE, P.DESCRIPCION, P.MODULO
    FROM ROL_PERMISO RP
    INNER JOIN PERMISO P ON RP.ID_PERMISO = P.ID_PERMISO
    WHERE RP.ID_ROL = @IdRol;
END
GO

CREATE PROCEDURE sp_TodosLosPermisos
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ID_PERMISO, CLAVE, DESCRIPCION, MODULO FROM PERMISO ORDER BY MODULO, CLAVE;
END
GO

-- Asignar un permiso a un rol (idempotente)
CREATE PROCEDURE sp_AsignarPermiso
    @IdRol INT, @IdPermiso INT
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT EXISTS (SELECT 1 FROM ROL_PERMISO WHERE ID_ROL=@IdRol AND ID_PERMISO=@IdPermiso)
        INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO) VALUES (@IdRol, @IdPermiso);
END
GO

-- Quitar un permiso a un rol
CREATE PROCEDURE sp_QuitarPermiso
    @IdRol INT, @IdPermiso INT
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM ROL_PERMISO WHERE ID_ROL=@IdRol AND ID_PERMISO=@IdPermiso;
END
GO

CREATE PROCEDURE sp_ListarRoles
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ID_ROL, NOMBRE, ESTADO FROM ROL WHERE ESTADO='ACTIVO' ORDER BY NOMBRE;
END
GO

-- ---- CLIENTES (CRUD) ----
CREATE PROCEDURE sp_Cliente_Listar
AS
BEGIN
    SET NOCOUNT ON;
    SELECT CEDULA, NOMBRE, TELEFONO, DIRECCION, CORREO, TIPO, FECHA_REGISTRO, ESTADO
    FROM CLIENTE WHERE ESTADO='ACTIVO' ORDER BY NOMBRE;
END
GO

CREATE PROCEDURE sp_Cliente_Insertar
    @Cedula VARCHAR(20), @Nombre VARCHAR(100), @Telefono VARCHAR(20),
    @Direccion VARCHAR(200), @Correo VARCHAR(100), @Tipo VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO CLIENTE (CEDULA, NOMBRE, TELEFONO, DIRECCION, CORREO, TIPO)
    VALUES (@Cedula, @Nombre, @Telefono, @Direccion, @Correo, @Tipo);
END
GO

CREATE PROCEDURE sp_Cliente_Actualizar
    @Cedula VARCHAR(20), @Nombre VARCHAR(100), @Telefono VARCHAR(20),
    @Direccion VARCHAR(200), @Correo VARCHAR(100), @Tipo VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE CLIENTE SET NOMBRE=@Nombre, TELEFONO=@Telefono, DIRECCION=@Direccion,
        CORREO=@Correo, TIPO=@Tipo WHERE CEDULA=@Cedula;
END
GO

CREATE PROCEDURE sp_Cliente_Eliminar
    @Cedula VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE CLIENTE SET ESTADO='INACTIVO' WHERE CEDULA=@Cedula;  -- eliminación lógica
END
GO

-- ---- VEHICULOS (CRUD) ----
CREATE PROCEDURE sp_Vehiculo_Listar
AS
BEGIN
    SET NOCOUNT ON;
    SELECT V.PLACA, V.MARCA, V.MODELO, V.ANIO, V.COLOR, V.NUMERO_CHASIS, V.NUMERO_MOTOR,
           V.TIPO_COMBUSTIBLE, V.KILOMETRAJE, V.CLIENTE_CEDULA, C.NOMBRE AS CLIENTE_NOMBRE, V.ESTADO
    FROM VEHICULO V INNER JOIN CLIENTE C ON V.CLIENTE_CEDULA = C.CEDULA
    WHERE V.ESTADO='ACTIVO' ORDER BY V.PLACA;
END
GO

CREATE PROCEDURE sp_Vehiculo_Insertar
    @Placa VARCHAR(10), @Marca VARCHAR(50), @Modelo VARCHAR(50), @Anio INT,
    @Color VARCHAR(30), @NumChasis VARCHAR(50), @NumMotor VARCHAR(50),
    @TipoComb VARCHAR(20), @Kilometraje INT, @ClienteCedula VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO VEHICULO (PLACA, MARCA, MODELO, ANIO, COLOR, NUMERO_CHASIS, NUMERO_MOTOR,
        TIPO_COMBUSTIBLE, KILOMETRAJE, CLIENTE_CEDULA)
    VALUES (@Placa, @Marca, @Modelo, @Anio, @Color, @NumChasis, @NumMotor,
        @TipoComb, @Kilometraje, @ClienteCedula);
END
GO

CREATE PROCEDURE sp_Vehiculo_Actualizar
    @Placa VARCHAR(10), @Marca VARCHAR(50), @Modelo VARCHAR(50), @Anio INT,
    @Color VARCHAR(30), @NumChasis VARCHAR(50), @NumMotor VARCHAR(50),
    @TipoComb VARCHAR(20), @Kilometraje INT, @ClienteCedula VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE VEHICULO SET MARCA=@Marca, MODELO=@Modelo, ANIO=@Anio, COLOR=@Color,
        NUMERO_CHASIS=@NumChasis, NUMERO_MOTOR=@NumMotor, TIPO_COMBUSTIBLE=@TipoComb,
        KILOMETRAJE=@Kilometraje, CLIENTE_CEDULA=@ClienteCedula WHERE PLACA=@Placa;
END
GO

CREATE PROCEDURE sp_Vehiculo_Eliminar
    @Placa VARCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE VEHICULO SET ESTADO='INACTIVO' WHERE PLACA=@Placa;
END
GO

-- ---- EMPLEADOS (CRUD) ----
CREATE PROCEDURE sp_Empleado_Listar
AS
BEGIN
    SET NOCOUNT ON;
    SELECT E.CEDULA, E.NOMBRE, E.TELEFONO, E.DIRECCION, E.CARGO, E.FECHA_INGRESO,
           E.SALARIO, E.ESPECIALIDAD, E.USUARIO, E.ID_ROL, R.NOMBRE AS ROL_NOMBRE, E.ESTADO
    FROM EMPLEADO E INNER JOIN ROL R ON E.ID_ROL=R.ID_ROL
    WHERE E.ESTADO='ACTIVO' ORDER BY E.NOMBRE;
END
GO

CREATE PROCEDURE sp_Empleado_Insertar
    @Cedula VARCHAR(20), @Nombre VARCHAR(100), @Telefono VARCHAR(20), @Direccion VARCHAR(200),
    @Cargo VARCHAR(30), @Salario DECIMAL(10,2), @Especialidad VARCHAR(100),
    @Usuario VARCHAR(50), @HashClave VARCHAR(64), @IdRol INT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO EMPLEADO (CEDULA, NOMBRE, TELEFONO, DIRECCION, CARGO, SALARIO,
        ESPECIALIDAD, USUARIO, CONTRASENA, ID_ROL)
    VALUES (@Cedula, @Nombre, @Telefono, @Direccion, @Cargo, @Salario,
        @Especialidad, @Usuario, @HashClave, @IdRol);
END
GO

CREATE PROCEDURE sp_Empleado_Actualizar
    @Cedula VARCHAR(20), @Nombre VARCHAR(100), @Telefono VARCHAR(20), @Direccion VARCHAR(200),
    @Cargo VARCHAR(30), @Salario DECIMAL(10,2), @Especialidad VARCHAR(100), @IdRol INT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE EMPLEADO SET NOMBRE=@Nombre, TELEFONO=@Telefono, DIRECCION=@Direccion,
        CARGO=@Cargo, SALARIO=@Salario, ESPECIALIDAD=@Especialidad, ID_ROL=@IdRol
    WHERE CEDULA=@Cedula;
END
GO

CREATE PROCEDURE sp_Empleado_Eliminar
    @Cedula VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE EMPLEADO SET ESTADO='INACTIVO' WHERE CEDULA=@Cedula;
END
GO

-- ---- PRODUCTOS (CRUD + stock) ----
CREATE PROCEDURE sp_Producto_Listar
AS
BEGIN
    SET NOCOUNT ON;
    SELECT CODIGO, NOMBRE, CATEGORIA, MARCA, DESCRIPCION, STOCK_ACTUAL, STOCK_MINIMO,
           PRECIO_COMPRA, PRECIO_VENTA, ESTADO
    FROM PRODUCTO WHERE ESTADO='ACTIVO' ORDER BY NOMBRE;
END
GO

CREATE PROCEDURE sp_Producto_Insertar
    @Codigo VARCHAR(20), @Nombre VARCHAR(100), @Categoria VARCHAR(50), @Marca VARCHAR(50),
    @Descripcion VARCHAR(500), @StockActual INT, @StockMinimo INT,
    @PrecioCompra DECIMAL(10,2), @PrecioVenta DECIMAL(10,2)
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO PRODUCTO (CODIGO, NOMBRE, CATEGORIA, MARCA, DESCRIPCION, STOCK_ACTUAL,
        STOCK_MINIMO, PRECIO_COMPRA, PRECIO_VENTA)
    VALUES (@Codigo, @Nombre, @Categoria, @Marca, @Descripcion, @StockActual,
        @StockMinimo, @PrecioCompra, @PrecioVenta);
END
GO

CREATE PROCEDURE sp_Producto_Actualizar
    @Codigo VARCHAR(20), @Nombre VARCHAR(100), @Categoria VARCHAR(50), @Marca VARCHAR(50),
    @Descripcion VARCHAR(500), @StockMinimo INT,
    @PrecioCompra DECIMAL(10,2), @PrecioVenta DECIMAL(10,2)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE PRODUCTO SET NOMBRE=@Nombre, CATEGORIA=@Categoria, MARCA=@Marca,
        DESCRIPCION=@Descripcion, STOCK_MINIMO=@StockMinimo,
        PRECIO_COMPRA=@PrecioCompra, PRECIO_VENTA=@PrecioVenta WHERE CODIGO=@Codigo;
END
GO

CREATE PROCEDURE sp_Producto_Eliminar
    @Codigo VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE PRODUCTO SET ESTADO='INACTIVO' WHERE CODIGO=@Codigo;
END
GO

CREATE PROCEDURE sp_Producto_AlertasStockMinimo
AS
BEGIN
    SET NOCOUNT ON;
    SELECT CODIGO, NOMBRE, STOCK_ACTUAL, STOCK_MINIMO
    FROM PRODUCTO WHERE ESTADO='ACTIVO' AND STOCK_ACTUAL <= STOCK_MINIMO;
END
GO

-- ---- AUDITORÍA ----
CREATE PROCEDURE sp_Auditoria_Registrar
    @Usuario VARCHAR(50), @Modulo VARCHAR(50), @Operacion VARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO AUDITORIA (USUARIO, MODULO, OPERACION) VALUES (@Usuario, @Modulo, @Operacion);
END
GO

PRINT '====================================================';
PRINT ' Base de datos TallerJuanDB creada correctamente.';
PRINT ' Usuario: juan   /   Contraseña: juan';
PRINT '====================================================';
GO
